name: update-flutter-web

permissions:

  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v4

        with:

          fetch-depth: 0

      - name: Determine Flutter version

        id: flutter-version

        run: |

          FLUTTER_VERSION="stable"

          if [ -f version.txt ] && [ -s version.txt ]; then

            FLUTTER_VERSION=$(cat version.txt)

          fi

          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

          echo "Using Flutter version: $FLUTTER_VERSION"

      - name: Set up Flutter

        uses: subosito/flutter-action@v2

        with:

          flutter-version: ${{ env.FLUTTER_VERSION }}

          channel: stable

      - name: Show Flutter & Dart versions

        run: |

          flutter --version

          dart --version

      - name: Install dependencies

        run: flutter pub get

      - name: Build Flutter Web

        run: flutter build web --release --base-href="/Truestay/"

      - name: Deploy to GitHub Pages

        uses: peaceiris/actions-gh-pages@v4

        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: build/web