name: update-flutter-web

on:
  push:
    branches:
      - main
      - update-flutter-web
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.1
          channel: stable

      - name: Cache Flutter Pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: flutter-cache-3.35.1-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-cache-3.35.1-

      - name: Show Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Clean previous build
        run: |
          if [ -d build/web ]; then
            rm -rf build/web
          fi

      - name: Determine GitHub Pages base href
        id: base-href
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          echo "BASE_HREF=/$REPO_NAME/" >> $GITHUB_ENV
          echo "Using base href: /$REPO_NAME/"

      - name: Build Flutter Web
        run: flutter build web --release --base-href="${{ env.BASE_HREF }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
