name: flutter-web

on:
  push:
    branches: [ main, update-flutter-web ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: flutter-web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Flutter version
        id: flutter-version
        shell: bash
        run: |
          DEFAULT_VERSION="3.19.1"
          if [[ -f version.txt ]]; then
            RAW=$(tr -d '\r\n' < version.txt)
            if [[ "$RAW" =~ ^[0-9]+(\.[0-9]+)*([-/][A-Za-z0-9\.\-]+)?$ || "$RAW" == "stable" || "$RAW" == "beta" || "$RAW" == "master" ]]; then
              FLUTTER_VERSION="$RAW"
              echo "::notice::Using Flutter version from version.txt: $FLUTTER_VERSION"
            else
              FLUTTER_VERSION="$DEFAULT_VERSION"
              echo "::warning::Invalid version in version.txt ('$RAW'). Using default: $FLUTTER_VERSION"
            fi
          else
            FLUTTER_VERSION="$DEFAULT_VERSION"
            echo "::notice::version.txt not found. Using default: $FLUTTER_VERSION"
          fi
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> "$GITHUB_ENV"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Cache Flutter Pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Show Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Clean previous build
        run: rm -rf build/web

      - name: Determine GitHub Pages base href
        id: base-href
        shell: bash
        run: |
          OWNER="${GITHUB_REPOSITORY%%/*}"
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          lo_owner=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          lo_repo=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          if [[ "$lo_repo" == "${lo_owner}.github.io" ]]; then
            BASE_HREF="/"
          else
            BASE_HREF="/$REPO_NAME/"
          fi
          echo "BASE_HREF=$BASE_HREF" >> "$GITHUB_ENV"
          echo "::notice::Using base href: $BASE_HREF"

      - name: Build Flutter Web
        run: flutter build web --release --base-href "${{ env.BASE_HREF }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
